module.exports = function(User) {
  User.disableRemoteMethod('__count__accessTokens', false)
  User.disableRemoteMethod('__create__accessTokens', false)
  User.disableRemoteMethod('__delete__accessTokens', false)
  User.disableRemoteMethod('__destroyById__credentials', false)
  User.disableRemoteMethod('__destroyById__accessTokens', false)
  User.disableRemoteMethod('__findById__accessTokens', false)
  User.disableRemoteMethod('__findById__credentials', false)
  User.disableRemoteMethod('__getById__credentials', false)
  User.disableRemoteMethod('__createById__credentials', false)
  User.disableRemoteMethod('__updateById__credentials', false)
  User.disableRemoteMethod('__get__accessTokens', false)
  User.disableRemoteMethod('__updateById__accessTokens', false)
  User.disableRemoteMethod('__updateById__accessTokens', false)
  User.disableRemoteMethod('__updateById__accessTokens', false)
  User.disableRemoteMethod('__updateById__accessTokens', false)

  User.disableRemoteMethod('findOne', true)
  User.disableRemoteMethod('confirm', true)
  User.disableRemoteMethod('count', true)
  User.disableRemoteMethod('createChangeStream', true)
  User.disableRemoteMethod('exists', true)
};
